config/routes.rb
Rails.application.routes.draw do

  root to:'home#index'
  devise_for :users
  
  resources :users do
      resources :campaign_tabs do 
      resources :tags
      resources :todos
      resources :comments
      resources :topics do
        resources :comments
      end
    end
  end
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commented_on , polymorphic: true
  
  validates :title, :user_id ,:presence => {:message => "dont't leave blank "}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 before_action :get_comment, only:[:show, :edit, :update, :destroy]  
 before_action :get_campaign
 before_action :get_topic
    def index
    end

    def new
    if @topic.present?
      @comment = @topic.comments.new
    else
      @comment = @campaign.comments.new
    end
    end

    def create
      if @topic.present?
        @comment = @topic.comments.new(comment_params)
        if @comment.save
          redirect_to  user_campaign_tab_topic_path(current_user.id,@campaign, @topic)
      else
          render 'new'
      end
      else
        @comment = @campaign.comments.new(comment_params)
        if @comment.save
          redirect_to user_campaign_tab_path(current_user.id,@comment.commented_on_id)
      else
          render 'new'
      end
      end
       
    end
    
    def edit 
    end

    def update
        if @comment.update(comment_params)
          if @topic.present?
            redirect_to user_campaign_tab_topic_comment_path(current_user.id,@campaign,@topic,@comment.id)
          else
            redirect_to user_campaign_tab_comment_path(current_user.id,@campaign,@comment.id)
          end    
        else
            render 'edit'
        end
    end

    def show 
    end
    
    def destroy
        c = @comment
        @comment.destroy
        if c.commented_on_type == "Topic"
            redirect_to user_campaign_tab_topic_path(current_user.id,@campaign,@topic)
        elsif c.commented_on_type == "CampaignTab"
            redirect_to user_campaign_tab_path(current_user.id,@campaign.id)
        end
    end

private

    def get_campaign
      @campaign = CampaignTab.find(params[:campaign_tab_id])
    end

    def get_topic
      if request.url.to_s.include? "topics"
      @topic = Topic.find(params[:topic_id])
      end
    end



  def get_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:title, :user_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
    
    def commented_on(comment)
        if comment.commented_on_type == "Topic"
            return true
        else
            return false
        end
    end

end

app/views/comments/_form.html.erb
<% if @topic.present?%>
<%= form_for [current_user,@campaign,@topic, comment] do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-floating mb-3">
    <%= f.text_field :title,id:"floatingInput",class:"form-control", placeholder:"aa" %>
      <%= f.label :title , for:"floatingInput" %>
  </div>

  <div class="field form-floating mb-3">
    <%= f.text_field :user_id, value:current_user.id, hidden:true ,id:"floatingInput",class:"form-control", placeholder:"aa" %>
  </div>
  
  <div class="actions">
    <%= f.submit class:"btn btn-outline-warning"%>
  </div>
<% end %>
<%else%>
<%= form_for [current_user,@campaign, comment] do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-floating mb-3">
    <%= f.text_field :title,id:"floatingInput",class:"form-control", placeholder:"aa" %>
      <%= f.label :title , for:"floatingInput" %>
  </div>

  <div class="field form-floating mb-3">
    <%= f.text_field :user_id, value:current_user.id, hidden:true ,id:"floatingInput",class:"form-control", placeholder:"aa" %>
  </div>
  
  <div class="actions">
    <%= f.submit class:"btn btn-outline-warning"%>
  </div>
  <%end%>
<%end%>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>
<br>
<% if commented_on(@comment)%>
<%= link_to 'Back', user_campaign_tab_topic_path(current_user.id,@campaign,@comment.commented_on_id) , class:"btn btn-outline-secondary"%>
<%else%>
<%= link_to 'Back', user_campaign_tab_path(current_user.id,@comment.commented_on_id), class:"btn btn-outline-secondary" %>
<%end%>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>
<br>
<% if commented_on(@comment)%>
<%= link_to 'Back',  user_campaign_tab_topic_path(current_user.id,@campaign,@comment.commented_on_id) , class:"btn btn-outline-secondary"%>
<% else%>
<%= link_to 'Back', user_campaign_tab_path(current_user.id,@comment.commented_on_id), class:"btn btn-outline-secondary" %>
<%end%>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">
    <strong>Title:</strong>
  <%= @comment.title %>
  </h5>
    
<%if current_user.id == @comment.user_id%>
<% if @topic.present?%>
<%= link_to 'Edit', edit_user_campaign_tab_topic_comment_path(current_user.id,@campaign,@topic,@comment.id) , class:"btn btn-outline-secondary btn-sm"%> 
<%= link_to 'Destroy', [current_user,@campaign,@topic,@comment], method: :delete, data: { confirm: 'Are you sure?' } ,class:"btn btn-outline-danger btn-sm"%> 
<%else%>
<%= link_to 'Edit', edit_user_campaign_tab_comment_path(current_user.id,@campaign,@comment.id) , class:"btn btn-outline-secondary btn-sm"%> 
<%= link_to 'Destroy', [current_user,@campaign,@comment], method: :delete, data: { confirm: 'Are you sure?' } ,class:"btn btn-outline-danger btn-sm"%> 
<%end%>
<%end%>
  </div>
</div>

<br>


<% if commented_on(@comment)%>
<%= link_to 'Back', user_campaign_tab_topic_path(current_user.id,@campaign,@comment.commented_on_id) ,class:"btn btn-outline-dark btn-sm" %>
<%else%>
<%= link_to 'Back', user_campaign_tab_path(current_user.id,@comment.commented_on_id) ,class:"btn btn-outline-dark btn-sm"%>
<%end%>