config/routes.rb
Rails.application.routes.draw do

  root to:'home#index'
  devise_for :users
  
  resources :users do
      resources :campaign_tabs do 
      resources :tags
      resources :todos
      resources :comments
      resources :topics do
        resources :comments
      end
    end
  end
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  belongs_to :campaign_tab
  has_many :comments, as: :commented_on, dependent: :destroy

  validates :title, :user_id, :campaign_tab_id, :presence => {:message => "dont't leave blank "}
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
    before_action :get_campaign
    before_action :get_topic, only:[:show,:edit, :destroy, :update]
   
    def index
    end
    
  def new
        #finding topics if current user created any
        topics = Topic.all
            topics.each do |t|
                #if current user created topic for current
                #campaign user then show error page
            if t.user_id == current_user.id
                found_expert = CampaignTab.find(t.campaign_tab_id).user_id
                if found_expert != nil && found_expert == @campaign.user_id
                    render "error"
                end
            end
        end
        @topic = @campaign.topics.new
    end

    def create
        @topic = @campaign.topics.new(topic_params)
        if @topic.save
            redirect_to user_campaign_tab_topic_path(current_user.id,@campaign, @topic)
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @topic.update(topic_params)
            redirect_to user_campaign_tab_topic_path(current_user.id,@campaign, @topic)
        else
            render 'edit'
        end
    end

    def show
    end

    def destroy
        @topic.destroy
        redirect_to user_campaign_tab_path(current_user.id,@topic.campaign_tab_id)
    end

 private
    
    def get_campaign
        @campaign = CampaignTab.find(params[:campaign_tab_id])
    end

    def get_topic
        @topic = @campaign.topics.find(params[:id])
    end 

    def topic_params
        params.require(:topic).permit(:title, :user_id, :campaign_tab_id)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper

    def get_user(topic)
        return true if topic.user_id == current_user.id
        return false
    end
    
    def get_comments(t)
        return t.comments.all
    end
end

app/views/topics/_form.html.erb
<%= form_for [current_user,@campaign,topic] do |f| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-floating mb-3">
    <%= f.text_field :title , id:"floatingInput",class:"form-control", placeholder:"aa" %>
     <%= f.label :title ,for:"floatingInput" %>
  </div>
   
   <div class="field form-floating mb-3">
    <%= f.text_field :user_id, value: current_user.id, hidden:true , id:"floatingInput",class:"form-control", placeholder:"aa" %>
  </div>

  <div class="field form-floating mb-3">
    <%= f.text_field :campaign_tab_id, value: @campaign.id, hidden:true , id:"floatingInput",class:"form-control", placeholder:"aa" %>
  </div>

  <div class="actions">
    <%= f.submit  class:"btn btn-outline-info"%>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>
<br>
<%= link_to 'Show', user_campaign_tab_topic_path(current_user.id,@campaign, @topic) , class:"btn btn-outline-info" %> 
<%= link_to 'Back', user_campaign_tab_path(current_user.id,@topic.campaign_tab_id), class:"btn btn-outline-secondary" %>

app/views/topics/error.html.erb
<br>
<h1 class="buttons" style="color:red">You already created topics against this campaign user</h1>
<br><br><br>
<div class="buttons"><%= link_to 'Back', user_campaign_tab_path(current_user.id,@campaign.id), class:"btn btn-outline-secondary " %></div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form', topic: @topic %>
<br>
<%= link_to 'Back', user_campaign_tab_path(current_user.id,@campaign.id), class:"btn btn-outline-secondary" %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card" style="width: 20rem;">
  <div class="card-body">
    <h5 class="card-title">
    <strong>Title:</strong>
  <%= @topic.title %>
    </h5>
<%= link_to 'Comment', new_user_campaign_tab_topic_comment_path(current_user.id,@campaign,@topic), class:"btn btn-outline-warning btn-sm " %> 
<% if get_user(@topic)%>
<%= link_to 'Edit', edit_user_campaign_tab_topic_path(current_user.id,@campaign,@topic) ,class:"btn btn-outline-secondary btn-sm " %> 
<%= link_to 'Destroy', [current_user,@campaign,@topic], method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm " %>
<%end%>
<%= link_to 'Back', user_campaign_tab_path(current_user.id,@topic.campaign_tab_id), class:"btn btn-outline-dark btn-sm " %> 
  </div>
</div>
<br>
<br>
<div class="buttons"><strong>Comments</strong><br></div>
<br><br>
<% arr = get_comments(@topic)%>
<% arr.each do |c|%>
 <%=link_to  c.title,  user_campaign_tab_topic_comment_path(current_user.id,@campaign,@topic,c.id), class:"comment bg-light border buttons"%>
<br>
<%end%>