config/routes.rb
Rails.application.routes.draw do

  root to:'home#index'
  devise_for :users
  
  resources :users do
      resources :campaign_tabs do 
      resources :tags
      resources :todos
      resources :comments
      resources :topics do
        resources :comments
      end
    end
  end
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/campaign_tab.rb
class CampaignTab < ApplicationRecord
  belongs_to :user
  has_many :topics , dependent: :destroy
  has_many :comments, as: :commented_on, dependent: :destroy
  has_many :todo , dependent: :destroy
  has_many :tags , dependent: :destroy
    
  validates :title, :purpose, :estimated_duration,:user_id, :presence => {:message => "dont't leave blank "}
end

app/controllers/campaign_tabs_controller.rb
class CampaignTabsController < ApplicationController
    before_action :get_campaign, only:[:show, :edit, :update, :destroy ]
    
    def index
    end 
    
    def new
        @campaign_tab = CampaignTab.new
    end

    def create
        @campaign_tab = CampaignTab.new(campaign_tab_params)
        if @campaign_tab.save
            redirect_to user_campaign_tab_path(current_user,@campaign_tab)
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @campaign_tab.update(campaign_tab_params)
            redirect_to root_path
        else
            render 'edit'
        end
    end

    def show
    end

    def destroy
        @campaign_tab.destroy
        redirect_to root_path
    end

private

    def get_campaign
        @campaign_tab = CampaignTab.find(params[:id])
    end
    

    def campaign_tab_params
        params.require(:campaign_tab).permit(:title, :purpose, :estimated_duration,:user_id)
    end

end

app/helpers/campaign_tabs_helper.rb
module CampaignTabsHelper
    
    def find_topics(campaign_tab)
        arr = Array.new
        topics = Topic.all
        topics.each do |t|
            if t.campaign_tab_id == campaign_tab.id
            arr.push(t)
            end
        end
        return arr
    end

    def find_tags(campaign_tab)
        arr = Array.new
        tag = Tag.all
        tag.each do |t|
            if t.campaign_tab_id == campaign_tab.id
            arr.push(t)
            end
        end
        return arr
    end

    def find_todo(campaign_tab)
         t = Todo.where(campaign_tab_id: campaign_tab.id)
         if t != nil
            return t.to_a
        else
            return nil 
        end
    end
   
    def get_comments(c)
        return c.comments.all
    end
end

app/views/campaign_tabs/_form.html.erb
<%= form_for [current_user,campaign_tab] do |f| %>
  <% if campaign_tab.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(campaign_tab.errors.count, "error") %> prohibited this campaign_tab from being saved:</h2>

      <ul>
      <% campaign_tab.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-floating mb-3">
    <%= f.text_field :title,id:"floatingInput",class:"form-control", placeholder:"aa" %>
    <%= f.label :title , for:"floatingInput"%>
  </div>

  <div class="field form-floating mb-3">
    <%= f.text_field :purpose,id:"floatingInput",class:"form-control", placeholder:"aa" %>
    <%= f.label :purpose , for:"floatingInput"%>
  </div>

  <div class="field form-floating mb-3">
    <%= f.select :estimated_duration, options_for_select([["within 1 week",7],["within 1 month",30],["within 3 months",90]]), class:"form-select form-select-sm", id:"floatingInput" %>
  </div>
  <br>
<div class="field form-floating mb-3">
  <%= f.text_field :user_id , value:current_user.id, hidden:true %>
  </div>

  <div class="actions">
    <%= f.submit class:"btn btn-primary btn-sm"%>
  </div>
<% end %>

app/views/campaign_tabs/edit.html.erb
<h1>Editing Campaign Tab</h1>

<%= render 'form', campaign_tab: @campaign_tab %>
<br>
<%= link_to 'Show', user_campaign_tab_path(current_user,@campaign_tab) , class:"btn btn-outline-dark btn-sm"%> 
<%= link_to 'Back', root_path , class:"btn btn-outline-secondary btn-sm"%>

app/views/campaign_tabs/new.html.erb
<h1>New Campaign</h1>

<%= render 'form', campaign_tab: @campaign_tab %>
<br>
<%= link_to 'Back', root_path, class:"btn btn-outline-secondary" %>

app/views/campaign_tabs/show.html.erb
<div class="card text-center">
  <div class="card-header">
    Campaign
  </div>
  <div class="card-body">
    <h5 class="card-title"> <%= @campaign_tab.title %></h5>
    <p class="card-text"> <%= @campaign_tab.purpose %></p>
    <strong class="text-success">Todos of this Campaign:</strong><br>
    <%todo_for_campaign = find_todo(@campaign_tab)%>
    <%if current_user.id == @campaign_tab.user_id%>
    <%todo_for_campaign.each do |todo|%>
    <p class="card-text"><%= link_to todo.title , edit_user_campaign_tab_todo_path(current_user.id,@campaign_tab, todo), class:"lnk" %></p>
    <%end%>
     <%else%>
     <%todo_for_campaign.each do |todo|%>
    <p class="card-text"><%=todo.title %></p>
    <%end%>
    <%end%>

    <strong class="text-success">Topics:</strong><br>
    <% all_topics = find_topics(@campaign_tab)%>
    <% all_topics.each do |t|%>
    <%= link_to t.title, user_campaign_tab_topic_path(current_user.id,@campaign_tab, t) , class:"lnk" %>
    <%end%>
    <br>
    <br>
    <% if current_user.user_type == "novice" && current_user.status == "qualified" %>
    <%= link_to "Create Topic on this campaign", new_user_campaign_tab_topic_path(current_user,@campaign_tab) ,class:"btn btn-warning btn-sm" %>
    <%end%>
    <br>
    <br>
    <%= link_to 'Comment',  new_user_campaign_tab_comment_path(current_user.id,@campaign_tab),class:"btn btn-warning btn-sm" %> 
    <% if current_user.id == @campaign_tab.user_id%>
    <%= link_to "Add Todo", new_user_campaign_tab_todo_path(current_user.id,@campaign_tab) ,class:"btn btn-warning btn-sm" %> 
    <%= link_to "Add Tag", new_user_campaign_tab_tag_path(current_user.id,@campaign_tab) ,class:"btn btn-warning btn-sm" %>
    <%end%>
    <br>
    <strong>Tags:</strong><br>
    <% all_tags = find_tags(@campaign_tab)%>
    <% all_tags.each do |t|%>
    <%if current_user.id == t.user_id%>
    <%= link_to t.name, [current_user,@campaign_tab,t], method: :delete, data: { confirm: 'Are you sure want to delete this tag?' } , class:"badge bg-primary text-wrap" %>
    <%else%>
    <button class="badge bg-primary text-wrap"><%= t.name%></button>
    <%end%>
    <%end%>
  </div>
  <div class="card-footer text-muted">
    <strong>Estimated duration:</strong>
  <%= @campaign_tab.estimated_duration %> Days
  </div>
</div>
<br>
<div class="vstack gap-3">
<strong class="buttons">Comments</strong><br>
<% arr = get_comments(@campaign_tab)%>
<% arr.each do |c|%>
 <%=link_to  c.title, user_campaign_tab_comment_path(current_user.id,@campaign_tab, c.id), class:"comment bg-light border buttons"%>
<br>
<%end%>
</div>
<div class="buttons">
<%= link_to 'Back', root_path, class:"btn btn-outline-secondary btn-sm " %>
</div>
<br>