config/routes.rb
Rails.application.routes.draw do

  root to:'home#index'
  devise_for :users
  
  resources :users do
      resources :campaign_tabs do 
      resources :tags
      resources :todos
      resources :comments
      resources :topics do
        resources :comments
      end
    end
  end
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @campaign_tabs = CampaignTab.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
    def which_user(campaign_tab = 0)
        if campaign_tab != 0
         if campaign_tab.user_id == current_user.id
             return true
            end
        end
    end
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
  <div class="container-fluid">
    <%= link_to "Campaign App", root_path , class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
       
        <% if user_signed_in?%>
        <li class="nav-item">
             <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
             <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
        <%else%>
         <li class="nav-item">
             <%= link_to "Sign in", new_user_session_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
             <%= link_to "Sign up", new_user_registration_path, class:"nav-link" %>
        </li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<% if get_user_type%>
<div class="buttons">
<%= link_to "Create Campaign",new_user_campaign_tab_path(current_user.id), class:"btn btn-outline-dark btn-lg" %>
<%= link_to "Manage Users", users_path, class:"btn btn-outline-dark btn-lg "%>
</div>
<%end%>
<h4>All Campaigns</h4>
<table class="table table-striped table-hover"> 
  <thead class="table-dark">
    <tr>
      <th>Title</th>
      <th>Purpose</th>
      <th>Estimated duration</th>
      <th colspan="3" style="text-align:center">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @campaign_tabs.each do |campaign_tab| %>
      <tr>
        <td><%= campaign_tab.title %></td>
        <td><%= campaign_tab.purpose %></td>
        <td><%= campaign_tab.estimated_duration %> days</td>
        <td><%= link_to 'Show',  user_campaign_tab_path(current_user.id,campaign_tab), class:"btn btn-outline-secondary btn-sm" %></td>
        <%if which_user(campaign_tab)%>
        <td><%= link_to 'Edit', edit_user_campaign_tab_path(current_user.id,campaign_tab), class:"btn btn-outline-warning btn-sm" %></td>
        <td><%= link_to 'Destroy', [current_user, campaign_tab], class:"btn btn-outline-danger btn-sm",method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>